# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ch8_Covid19' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.4' 
  pod 'Charts'
  # Pods for ch8_Covid19

end
