# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ch1_SpotifyLoginSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ch1_SpotifyLoginSampleApp
  pod 'Firebase/Auth'

end
